pipeline {
    agent any
    stages {
        stage('Test') {
            steps {
                bat 'mvn --version'
                echo 'mvn --version'
            }
        }
        stage('Build') {
            steps {
                bat 'mvn package'
               echo 'mvn --build'
            }
              
        }
    }
}
