pipeline {
    agent any
    stages {
        stage('Test') {
            steps {
                bat 'mvn --version'
                echo 'mvn --version'
            }
        }
        stage('Build') {
            steps {
                bat 'mvn package'
               echo 'mvn --build'
            }
                        post {
            success {
            slackSend (color: '#00FF00', message: "SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")

            }
            failure {
            slackSend (color: '#FF0000', message: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")

            }
            }
        }
    }
}
